#!/usr/bin/env python3
r"""Generate golden differential vectors from CPython's codecs.

Usage:
    python tools/gen_vectors.py

Writes gen_w1252_vectors_wbtest.mbt to the repository root (name kept from
the windows-1252-only first milestone; the file now covers every WHATWG
legacy single-byte encoding).

Oracle design:
- For each encoding, every high byte is classified against CPython's
  independent implementation of the same code page:
    * clean      — both sides decode, same code point => usable as oracle
    * both-error — WHATWG index null AND CPython raises => agreement that the
                   byte is an error; our replacement semantics (U+FFFD) is
                   covered by a hand-written table-driven test instead
    * divergent  — everything else (CPython raises while WHATWG has a value,
                   or the values differ). Excluded from vectors and listed
                   in the generated file's header per encoding.
- Random samples draw from each encoding's clean byte pool plus printable
  ASCII; expected values come from CPython.
- The generator also cross-checks the encode direction: a character enters
  the encode vector pool only if CPython's encoder produces the same bytes
  as the WHATWG reverse index.

The five windows-1252 bytes 0x81/0x8D/0x8F/0x90/0x9D are the best-known
divergence case (CPython: UnicodeDecodeError; WHATWG: C1 controls), but the
classification is computed per encoding, not hardcoded.

The output embeds no Python version string: local and CI interpreters
differ, and the freshness check (generate + fmt + git diff) must not depend
on the interpreter version.

DO NOT edit the generated file by hand; re-run this script instead.
"""

import json
import pathlib
import random
import sys

import chinese_ref
import multibyte_ref

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
DATA = HERE / "data"

SINGLE_BYTE_GROUP = "Legacy single-byte encodings"
INDEX_KEY_ALIAS = {"ISO-8859-8-I": "iso-8859-8"}

# CPython codec names that do not follow the default mapping below.
PY_CODEC = {
    "IBM866": "cp866",
    "macintosh": "mac_roman",
    "x-mac-cyrillic": "mac_cyrillic",
    "ISO-8859-8-I": "iso8859_8",
    "windows-874": "cp874",
}

SEED = 0xC0FFEE
N_RANDOM_DECODE = 40
N_RANDOM_ENCODE = 25
MAX_SAMPLE_LEN = 32

HEADER = """// Generated by tools/gen_vectors.py — DO NOT EDIT.
//
// Oracle: CPython's codecs (an independent implementation of the same code
// pages). Regenerate with:
//     python tools/gen_vectors.py && moon fmt
//
// Bytes CPython cannot serve as an oracle for are excluded per encoding
// (listed below) and covered elsewhere:
//   * both-error bytes  -> our U+FFFD replacement path (hand-written test
//                          driven by the generated tables),
//   * divergent bytes   -> hand-written tests against the vendored spec
//                          table (e.g. the windows-1252 C1 controls).
"""


def moon_string(s: str) -> str:
    """Escape a Python string as a MoonBit string literal. Control
    characters (including newline, which would otherwise terminate the
    literal) and the C1 range are emitted as braced unicode escapes."""
    out = []
    for ch in s:
        o = ord(ch)
        if ch == chr(92):
            out.append(chr(92) * 2)
        elif ch == chr(34):
            out.append(chr(92) + chr(34))
        elif o < 0x20 or o == 0x7F or 0x80 <= o <= 0x9F:
            out.append(chr(92) + "u{" + format(o, "04X") + "}")
        else:
            out.append(ch)
    return chr(34) + "".join(out) + chr(34)


def moon_int_list(values) -> str:
    return "[" + ", ".join(f"0x{b:02X}" for b in values) + "]"


def load():
    encodings = json.loads((DATA / "encodings.json").read_text(encoding="utf-8"))
    indexes = json.loads((DATA / "indexes.json").read_text(encoding="utf-8"))
    group = next(g for g in encodings if g["heading"] == SINGLE_BYTE_GROUP)
    return list(group["encodings"]), indexes


def py_codec(name: str) -> str:
    if name in PY_CODEC:
        return PY_CODEC[name]
    ln = name.lower()
    if ln.startswith("iso-8859-"):
        return "iso8859_" + name.split("-")[-1]
    if ln.startswith("windows-12"):
        return "cp" + name.split("-")[-1]
    if ln == "koi8-r":
        return "koi8_r"
    if ln == "koi8-u":
        return "koi8_u"
    return ln.replace("-", "_")


def index_key(name: str) -> str:
    return INDEX_KEY_ALIAS.get(name, name.lower().replace("_", "-"))


def classify(index, codec: str):
    """Split high bytes into (clean, both_error, divergent) by comparing
    CPython's decoder against the WHATWG index."""
    clean, both_error, divergent = [], [], []
    for b in range(0x80, 0x100):
        w = index[b - 0x80]
        try:
            got = bytes([b]).decode(codec)
            py_cp = ord(got) if len(got) == 1 else "multichar"
        except UnicodeDecodeError:
            py_cp = None
        if w is None and py_cp is None:
            both_error.append(b)
        elif w is not None and py_cp == w:
            clean.append(b)
        else:
            divergent.append(b)
    return clean, both_error, divergent


def main() -> None:
    encs, indexes = load()
    rng = random.Random(SEED)

    per_encoding_stats = []
    decode_tests = []  # (name, [(bytes, expected)...])
    encode_tests = []  # (name, [(text, bytes)...])
    label_pairs = []

    ascii_bytes = list(range(0x20, 0x7F))
    ascii_text = "".join(chr(b) for b in ascii_bytes)

    for enc in encs:
        name = enc["name"]
        codec = py_codec(name)
        key = index_key(name)
        if key not in indexes:
            sys.exit(f"{name}: no index table (key {key!r})")
        index = indexes[key]
        clean, both_error, divergent = classify(index, codec)
        per_encoding_stats.append((name, len(clean), len(both_error), len(divergent)))

        label_pairs.append((name, name))  # canonical name folds to its own label
        label_pairs.append((enc["labels"][0], name))

        # ---- decode vectors ------------------------------------------------
        pool = clean + ascii_bytes
        dec_vectors = [([b], bytes([b]).decode(codec)) for b in clean]
        for _ in range(N_RANDOM_DECODE):
            sample = [rng.choice(pool) for _ in range(rng.randint(1, MAX_SAMPLE_LEN))]
            dec_vectors.append((sample, bytes(sample).decode(codec)))
        decode_tests.append((name, codec, dec_vectors))

        # ---- encode vectors ------------------------------------------------
        # Characters reachable in both tables at the same byte; CPython's
        # encoder and the WHATWG reverse index must agree byte for byte.
        reverse = {cp: b for b in range(0x80, 0x100) if (cp := index[b - 0x80]) is not None}
        encode_pool = set(ascii_bytes)
        excluded_chars = 0
        for b in clean:
            cp = ord(bytes([b]).decode(codec))
            try:
                if bytes([b]) == chr(cp).encode(codec) and reverse.get(cp) == b:
                    encode_pool.add(cp)
                else:
                    excluded_chars += 1
            except UnicodeEncodeError:
                excluded_chars += 1
        encode_pool = sorted(encode_pool)
        enc_vectors = []
        for _ in range(N_RANDOM_ENCODE):
            text = "".join(chr(rng.choice(encode_pool)) for _ in range(rng.randint(1, 24)))
            enc_vectors.append((text, list(text.encode(codec))))
        encode_tests.append((name, codec, enc_vectors))
        if excluded_chars:
            per_encoding_stats[-1] = per_encoding_stats[-1] + (excluded_chars,)

    # ---- emit ---------------------------------------------------------------
    lines = [HEADER, ""]
    lines.append("// Per-encoding oracle coverage (clean / both-error / divergent high bytes):")
    for stat in per_encoding_stats:
        name, n_clean, n_both, n_div = stat[:4]
        extra = f", encode-excluded chars={stat[4]}" if len(stat) > 4 else ""
        lines.append(f"//   {name:16s} clean={n_clean:3d} both-error={n_both:3d} divergent={n_div:3d}{extra}")
    lines.append("")

    # ASCII identity: shared by every encoding, generated once; spot-checked
    # through three unrelated labels so the shared fast path is exercised
    # beyond windows-1252.
    ascii_dec = [([b], chr(b)) for b in ascii_bytes]
    lines.append('test "python differential: ASCII printable identity via three encodings (generated)" {')
    lines.append("  let vectors : Array[(Array[Int], String)] = [")
    for bs, expect in ascii_dec:
        lines.append(f"    ({moon_int_list(bs)}, {moon_string(expect)}),")
    lines.append("  ]")
    lines.append("  for i in 0..<vectors.length() {")
    lines.append("    let (input, expect) = vectors[i]")
    lines.append("    let bytes = bytes_of_ints(input)")
    lines.append('    @test.assert_eq(decode(bytes, "windows-1252"), Ok(expect))')
    lines.append('    @test.assert_eq(decode(bytes, "iso-8859-2"), Ok(expect))')
    lines.append('    @test.assert_eq(decode(bytes, "koi8-r"), Ok(expect))')
    lines.append("  }")
    lines.append("}")
    lines.append("")

    for name, codec, vectors in decode_tests:
        lines.append(
            f'test "python differential: {name} decode vs CPython {codec} (generated)" {{'
        )
        lines.append("  let vectors : Array[(Array[Int], String)] = [")
        for bs, expect in vectors:
            lines.append(f"    ({moon_int_list(bs)}, {moon_string(expect)}),")
        lines.append("  ]")
        lines.append(f'  let label = "{name}"')
        lines.append("  for i in 0..<vectors.length() {")
        lines.append("    let (input, expect) = vectors[i]")
        lines.append("    @test.assert_eq(decode(bytes_of_ints(input), label), Ok(expect))")
        lines.append("  }")
        lines.append("}")
        lines.append("")

    for name, codec, vectors in encode_tests:
        lines.append(
            f'test "python differential: {name} encode vs CPython {codec} (generated)" {{'
        )
        lines.append("  let vectors : Array[(String, Array[Int])] = [")
        for text, bs in vectors:
            lines.append(f"    ({moon_string(text)}, {moon_int_list(bs)}),")
        lines.append("  ]")
        lines.append(f'  let label = "{name}"')
        lines.append("  for i in 0..<vectors.length() {")
        lines.append("    let (text, expect) = vectors[i]")
        lines.append("    @test.assert_eq(encode(text, label), Ok(bytes_of_ints(expect)))")
        lines.append("  }")
        lines.append("}")
        lines.append("")

    lines.append('test "labels: single-byte names and first labels resolve (generated)" {')
    lines.append("  let pairs : Array[(String, String)] = [")
    for label, canonical in label_pairs:
        lines.append(f"    ({moon_string(label)}, {moon_string(canonical)}),")
    lines.append("  ]")
    lines.append("  for i in 0..<pairs.length() {")
    lines.append("    let (label, canonical) = pairs[i]")
    lines.append("    @test.assert_eq(label_to_encoding(label), Ok(canonical))")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    # ---- GBK / gb18030 ---------------------------------------------------
    for stats, dec_vecs, enc_vecs in chinese_ref.gen_vectors(indexes, rng):
        name, codec, _, _, n_skip, n_div = stats
        lines.append(f"// {name}: CPython-error skips={n_skip}, spec/CPython divergent={n_div}")
        lines.append("")
        lines.append(f'test "python differential: {name} decode vs CPython {codec} (generated)" {{')
        lines.append("  let vectors : Array[(Array[Int], String)] = [")
        for bs, expect in dec_vecs:
            lines.append(f"    ({moon_int_list(bs)}, {moon_string(expect)}),")
        lines.append("  ]")
        lines.append(f'  let label = "{name}"')
        lines.append("  for i in 0..<vectors.length() {")
        lines.append("    let (input, expect) = vectors[i]")
        lines.append("    @test.assert_eq(decode(bytes_of_ints(input), label), Ok(expect))")
        lines.append("  }")
        lines.append("}")
        lines.append("")
        lines.append(f'test "python differential: {name} encode vs CPython {codec} (generated)" {{')
        lines.append("  let vectors : Array[(String, Array[Int])] = [")
        for text, bs in enc_vecs:
            lines.append(f"    ({moon_string(text)}, {moon_int_list(bs)}),")
        lines.append("  ]")
        lines.append(f'  let label = "{name}"')
        lines.append("  for i in 0..<vectors.length() {")
        lines.append("    let (text, expect) = vectors[i]")
        lines.append("    @test.assert_eq(encode(text, label), Ok(bytes_of_ints(expect)))")
        lines.append("  }")
        lines.append("}")
        lines.append("")

    # ---- Big5 / Shift_JIS ------------------------------------------------
    for stats, dec_vecs, enc_vecs in multibyte_ref.gen_vectors(indexes, rng):
        name, codec, _, _, n_skip, n_div = stats
        lines.append(f"// {name}: CPython-error skips={n_skip}, spec/CPython divergent={n_div}")
        lines.append("")
        lines.append(f'test "python differential: {name} decode vs CPython {codec} (generated)" {{')
        lines.append("  let vectors : Array[(Array[Int], String)] = [")
        for bs, expect in dec_vecs:
            lines.append(f"    ({moon_int_list(bs)}, {moon_string(expect)}),")
        lines.append("  ]")
        lines.append(f'  let label = "{name}"')
        lines.append("  for i in 0..<vectors.length() {")
        lines.append("    let (input, expect) = vectors[i]")
        lines.append("    @test.assert_eq(decode(bytes_of_ints(input), label), Ok(expect))")
        lines.append("  }")
        lines.append("}")
        lines.append("")
        lines.append(f'test "python differential: {name} encode vs CPython {codec} (generated)" {{')
        lines.append("  let vectors : Array[(String, Array[Int])] = [")
        for text, bs in enc_vecs:
            lines.append(f"    ({moon_string(text)}, {moon_int_list(bs)}),")
        lines.append("  ]")
        lines.append(f'  let label = "{name}"')
        lines.append("  for i in 0..<vectors.length() {")
        lines.append("    let (text, expect) = vectors[i]")
        lines.append("    @test.assert_eq(encode(text, label), Ok(bytes_of_ints(expect)))")
        lines.append("  }")
        lines.append("}")
        lines.append("")

    out = ROOT / "gen_w1252_vectors_wbtest.mbt"
    out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    n_dec = sum(len(v) for _, _, v in decode_tests) + len(ascii_dec)
    n_enc = sum(len(v) for _, _, v in encode_tests)
    print(
        f"wrote {out.name}: {len(decode_tests)} decode suites ({n_dec} vectors), "
        f"{len(encode_tests)} encode suites ({n_enc} vectors), "
        f"{len(label_pairs)} label pairs"
    )


if __name__ == "__main__":
    main()
