#!/usr/bin/env python3
r"""Generate golden differential vectors from CPython's cp1252 codec.

Usage:
    python tools/gen_vectors.py

Writes gen_w1252_vectors_wbtest.mbt to the repository root. The vectors
assert our windows-1252 implementation against CPython's independent
implementation of the same Windows-1252 table.

Design notes:
- CPython's cp1252 leaves five bytes undefined (0x81 0x8D 0x8F 0x90 0x9D)
  and raises UnicodeDecodeError on them, while WHATWG maps them to the
  corresponding C1 controls. The generator *verifies* this divergence at
  generation time; the divergent bytes are excluded from vector comparison
  (they are covered by hand-written unit tests against the vendored spec
  table instead).
- Random samples avoid C0/C1 controls so expected strings need no
  \u{...} escapes; the ASCII control passthrough path is covered by a
  hand-written test.
- The output embeds no Python version string: local and CI interpreters
  differ, and the freshness check (generate + fmt + git diff) must not
  depend on the interpreter version.

DO NOT edit the generated file by hand; re-run this script instead.
"""

import json
import pathlib
import random
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent

# Bytes where CPython cp1252 and WHATWG windows-1252 disagree by design.
# CPython: undefined -> UnicodeDecodeError. WHATWG: mapped to C1 controls.
DIVERGENT = [0x81, 0x8D, 0x8F, 0x90, 0x9D]

SEED = 0xC0FFEE
N_RANDOM_DECODE = 100
N_RANDOM_ENCODE = 60
MAX_SAMPLE_LEN = 40

HEADER = """// Generated by tools/gen_vectors.py — DO NOT EDIT.
//
// Oracle: CPython's codecs 'cp1252' (an independent implementation of the
// same Windows-1252 table). Regenerate with:
//     python tools/gen_vectors.py && moon fmt
//
// The five bytes 0x81/0x8D/0x8F/0x90/0x9D are excluded here: CPython
// raises UnicodeDecodeError on them while WHATWG maps them to C1 controls.
// That divergence is verified at generation time and covered by the
// hand-written C1 tests in codec_wbtest.mbt / single_byte_wbtest.mbt.
"""


def moon_string(s: str) -> str:
    """Escape a Python string as a MoonBit string literal (inputs are
    guaranteed control-free by construction; only quotes/backslash need
    escaping)."""
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{out}"'


def moon_byte_list(bs) -> str:
    return "[" + ", ".join(f"0x{b:02X}" for b in bs) + "]"


def verify_divergence() -> None:
    """The whole design hinges on CPython rejecting exactly these bytes."""
    for b in range(256):
        try:
            bytes([b]).decode("cp1252")
            rejected = False
        except UnicodeDecodeError:
            rejected = True
        expect_rejected = b in DIVERGENT
        if rejected != expect_rejected:
            sys.exit(
                f"byte 0x{b:02X}: cp1252 rejects={rejected}, "
                f"expected={expect_rejected} — divergence set is stale"
            )


def main() -> None:
    verify_divergence()

    # ---- decode vectors -------------------------------------------------
    # 1) every clean high byte individually (the table values proper)
    dec_inputs = [[b] for b in range(0x80, 0x100) if b not in DIVERGENT]
    dec_expects = [bytes(x).decode("cp1252") for x in dec_inputs]
    # 2) printable ASCII individually
    for b in range(0x20, 0x7F):
        dec_inputs.append([b])
        dec_expects.append(bytes([b]).decode("cp1252"))
    n_table = len(dec_inputs)

    # 3) random byte strings over control-free, Python-decodable bytes
    rng = random.Random(SEED)
    pool = [b for b in range(0x20, 0x100) if b not in DIVERGENT]
    for _ in range(N_RANDOM_DECODE):
        sample = [rng.choice(pool) for _ in range(rng.randint(1, MAX_SAMPLE_LEN))]
        dec_inputs.append(sample)
        dec_expects.append(bytes(sample).decode("cp1252"))

    # ---- encode vectors -------------------------------------------------
    # text drawn from what CPython cp1252 can encode back to bytes;
    # single-char vectors only (random decode samples are multi-char)
    encodable = sorted({ord(s) for s in dec_expects[:n_table]} | set(range(0x20, 0x7F)))
    enc_texts, enc_expects = [], []
    for _ in range(N_RANDOM_ENCODE):
        text = "".join(chr(rng.choice(encodable)) for _ in range(rng.randint(1, 24)))
        enc_texts.append(text)
        enc_expects.append(list(text.encode("cp1252")))

    # sanity: our oracle strings must round-trip through cp1252 itself
    for text, want in zip(enc_texts, enc_expects):
        assert list(text.encode("cp1252")) == want

    lines = [HEADER, ""]
    lines.append(
        f"// {n_table} single-byte table vectors + {N_RANDOM_DECODE} random "
        f"decode samples + {N_RANDOM_ENCODE} random encode samples"
    )
    lines.append("")
    lines.append(
        'test "python differential: windows-1252 decode vs CPython cp1252 (generated)" {'
    )
    lines.append("  let inputs : Array[Array[Int]] = [")
    for x in dec_inputs:
        lines.append(f"    {moon_byte_list(x)},")
    lines.append("  ]")
    lines.append("  let expects : Array[String] = [")
    for s in dec_expects:
        lines.append(f"    {moon_string(s)},")
    lines.append("  ]")
    lines.append("  @test.assert_eq(inputs.length(), expects.length())")
    lines.append("  for i in 0..<inputs.length() {")
    lines.append(
        '    @test.assert_eq(decode(bytes_of_ints(inputs[i]), "windows-1252"), '
        "Ok(expects[i]))"
    )
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append(
        'test "python differential: windows-1252 encode vs CPython cp1252 (generated)" {'
    )
    lines.append("  let texts : Array[String] = [")
    for s in enc_texts:
        lines.append(f"    {moon_string(s)},")
    lines.append("  ]")
    lines.append("  let expects : Array[Array[Int]] = [")
    for x in enc_expects:
        lines.append(f"    {moon_byte_list(x)},")
    lines.append("  ]")
    lines.append("  @test.assert_eq(texts.length(), expects.length())")
    lines.append("  for i in 0..<texts.length() {")
    lines.append(
        '    @test.assert_eq(encode(texts[i], "windows-1252"), '
        "Ok(bytes_of_ints(expects[i])))"
    )
    lines.append("  }")
    lines.append("}")
    lines.append("")

    out = ROOT / "gen_w1252_vectors_wbtest.mbt"
    out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(
        f"wrote {out.name}: {len(dec_inputs)} decode vectors "
        f"({n_table} table + {N_RANDOM_DECODE} random), "
        f"{len(enc_texts)} encode vectors"
    )


if __name__ == "__main__":
    main()
