#!/usr/bin/env python3
"""Generate MoonBit table sources from the vendored WHATWG encoding data.

Usage:
    python tools/generate_tables.py

Reads tools/data/encodings.json and tools/data/indexes.json (vendored from
whatwg/encoding @ 2c3853e — the same revision encoding_rs pins for its own
table generation) and writes gen_label.mbt / gen_single_byte.mbt to the
repository root.

DO NOT edit the generated files by hand; re-run this script instead.
CI regenerates, runs `moon fmt`, and fails if the result differs from what
is committed.
"""

import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
DATA = HERE / "data"

REV = "2c3853e461afd718be198772170d024e427aee21"
SOURCE_URL = "https://github.com/whatwg/encoding"

HEADER = f"""// Generated by tools/generate_tables.py — DO NOT EDIT.
//
// Source: {SOURCE_URL} @ {REV}
// Data © WHATWG (Apple, Google, Mozilla, Microsoft); BSD 3-Clause License
// (see LICENSE-WHATWG in this repository).
"""

# Milestone F1 ships a single single-byte encoding end-to-end; later
# milestones widen this list (all 28 legacy single-byte encodings, then the
# multi-byte indexes).
SINGLE_BYTE_TARGETS = ["windows-1252"]

# Sentinel in decode tables: WHATWG index entry "null" -> decode error -> U+FFFD.
ERROR = -1


def load_sources():
    encodings = json.loads((DATA / "encodings.json").read_text(encoding="utf-8"))
    indexes = json.loads((DATA / "indexes.json").read_text(encoding="utf-8"))
    return encodings, indexes


def mangle(name: str) -> str:
    return name.upper().replace("-", "_").replace(" ", "_").replace(".", "_")


def fmt_array(values, per_line=8):
    chunks = [values[i : i + per_line] for i in range(0, len(values), per_line)]
    body = ",\n".join("  " + ", ".join(chunk) for chunk in chunks)
    return "[\n" + body + ",\n]"


def gen_labels(encodings) -> str:
    lines = [
        HEADER,
        "fn label_lookup(lowercase_label : String) -> Option[String] {",
        "  match lowercase_label {",
    ]
    n = 0
    for heading in encodings:
        for enc in heading["encodings"]:
            for label in enc["labels"]:
                # MoonBit match arms are separated by newlines, not commas.
                lines.append(f'    "{label}" => Some("{enc["name"]}")')
                n += 1
    lines += ["    _ => None", "  }", "}", ""]
    print(f"gen_label: {n} labels -> {sum(len(h['encodings']) for h in encodings)} encodings")
    return "\n".join(lines)


def gen_single_byte(indexes) -> str:
    parts = [HEADER]
    for name in SINGLE_BYTE_TARGETS:
        if name not in indexes:
            sys.exit(f"unknown single-byte encoding: {name}")
        index = indexes[name]  # 128 entries: bytes 0x80..0xFF -> code point | null
        if len(index) != 128:
            sys.exit(f"{name}: expected 128 index entries, got {len(index)}")
        decode = [f"0x{cp:04X}" if cp is not None else "-1" for cp in index]
        # reverse index for encoding: (code point, byte) pairs sorted by code point
        pairs = sorted((cp, i + 0x80) for i, cp in enumerate(index) if cp is not None)
        reverse = []
        for cp, byte in pairs:
            reverse.append(f"0x{cp:04X}")
            reverse.append(str(byte))
        null_pos = [f"0x{i + 0x80:02X}" for i, cp in enumerate(index) if cp is None]
        var = mangle(name)
        print(
            f"gen_single_byte: {name}: 128 decode entries "
            f"({len(null_pos)} decode-error bytes: {', '.join(null_pos) or 'none'}), "
            f"{len(pairs)} encodable high bytes"
        )
        parts.append(f"// {name}: byte 0x80..0xFF -> code point; -1 = decode error -> U+FFFD")
        parts.append(f"let {var.lower()}_decode : Array[Int] = {fmt_array(decode)}")
        parts.append("")
        parts.append(f"// {name}: (code point, byte) pairs sorted by code point, for encoding")
        parts.append(f"let {var.lower()}_encode : Array[Int] = {fmt_array(reverse)}")
        parts.append("")
    return "\n".join(parts)


def main():
    encodings, indexes = load_sources()
    (ROOT / "gen_label.mbt").write_text(gen_labels(encodings), encoding="utf-8", newline="\n")
    (ROOT / "gen_single_byte.mbt").write_text(gen_single_byte(indexes), encoding="utf-8", newline="\n")
    print("wrote gen_label.mbt, gen_single_byte.mbt")


if __name__ == "__main__":
    main()
