#!/usr/bin/env python3
"""Generate MoonBit table sources from the vendored WHATWG encoding data.

Usage:
    python tools/generate_tables.py

Reads tools/data/encodings.json and tools/data/indexes.json (vendored from
whatwg/encoding @ 2c3853e — the same revision encoding_rs pins for its own
table generation) and writes gen_label.mbt / gen_single_byte.mbt to the
repository root.

gen_single_byte.mbt contains, for every encoding in the WHATWG
"Legacy single-byte encodings" group:
- a decode table (byte 0x80..0xFF -> code point, -1 = index null = decode
  error -> U+FFFD under the standard's replacement semantics),
- an encode table (code point, byte pairs sorted by code point),
plus the `single_byte_tables` dispatch that codec.mbt uses, so the set of
wired encodings can never drift from the generated tables.

Emission is in moon fmt's fixpoint shape (comment block, blank line, `///|`
doc marker, declaration): moon 0.1.20260915's comment promotion needs two
fmt passes otherwise, and the CI freshness check only formats once.

DO NOT edit the generated files by hand; re-run this script instead.
CI regenerates, runs `moon fmt`, and fails if the result differs from what
is committed.
"""

import json
import pathlib
import sys

import multibyte_ref

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
DATA = HERE / "data"

REV = "2c3853e461afd718be198772170d024e427aee21"
SOURCE_URL = "https://github.com/whatwg/encoding"

HEADER = f"""// Generated by tools/generate_tables.py — DO NOT EDIT.
//
// Source: {SOURCE_URL} @ {REV}
// Data © WHATWG (Apple, Google, Mozilla, Microsoft); BSD 3-Clause License
// (see LICENSE-WHATWG in this repository).
"""

SINGLE_BYTE_GROUP = "Legacy single-byte encodings"
CHINESE_GROUP = "Legacy multi-byte Chinese (simplified) encodings"
TRADITIONAL_GROUP = "Legacy multi-byte Chinese (traditional) encodings"
JAPANESE_GROUP = "Legacy multi-byte Japanese encodings"
KOREAN_GROUP = "Legacy multi-byte Korean encodings"

# Encodings wired end-to-end in the multi-byte milestones. Each entry must be
# a member of one of the groups above (asserted at generation time); tables
# are only emitted for wired names, so unsupported encodings never leave
# unused tables behind (deny-warn would flag them).
MULTI_BYTE_WIRED = ["GBK", "gb18030", "Big5", "Shift_JIS", "EUC-JP", "EUC-KR"]

# Encoding name -> indexes.json key, where they differ. ISO-8859-8-I shares
# the ISO-8859-8 index (it is the logical-order label variant; the standard
# defines both against the same table).
INDEX_KEY_ALIAS = {"ISO-8859-8-I": "iso-8859-8"}

# Sentinel in decode tables: WHATWG index entry "null" -> decode error -> U+FFFD.
ERROR = -1


def load_sources():
    encodings = json.loads((DATA / "encodings.json").read_text(encoding="utf-8"))
    indexes = json.loads((DATA / "indexes.json").read_text(encoding="utf-8"))
    return encodings, indexes


def single_byte_encodings(encodings) -> list:
    for heading in encodings:
        if heading["heading"] == SINGLE_BYTE_GROUP:
            return list(heading["encodings"])
    sys.exit(f"encodings.json has no {SINGLE_BYTE_GROUP!r} group")


def chinese_encodings(encodings) -> list:
    for heading in encodings:
        if heading["heading"] == CHINESE_GROUP:
            return list(heading["encodings"])
    sys.exit(f"encodings.json has no {CHINESE_GROUP!r} group")


def gen_chinese(encodings, indexes) -> str:
    """Tables for the GBK/gb18030 pair.

    Per encoding.bs (GBK section): GBK's decoder *is* gb18030's decoder and
    GBK's encoder is gb18030's encoder with the is-GBK flag — so one state
    machine and one set of tables serve both names.
    """
    group_of = {
        "GBK": CHINESE_GROUP,
        "gb18030": CHINESE_GROUP,
        "Big5": TRADITIONAL_GROUP,
        "Shift_JIS": JAPANESE_GROUP,
        "EUC-JP": JAPANESE_GROUP,
        "EUC-KR": KOREAN_GROUP,
    }
    by_group = {h["heading"]: [e["name"] for e in h["encodings"]] for h in encodings}
    for name in MULTI_BYTE_WIRED:
        if name not in by_group.get(group_of[name], []):
            sys.exit(f"{name}: not a member of group {group_of[name]!r}")
    if by_group.get(TRADITIONAL_GROUP) != ["Big5"]:
        sys.exit(f"unexpected traditional group: {by_group.get(TRADITIONAL_GROUP)}")
    if by_group.get(KOREAN_GROUP) != ["EUC-KR"]:
        sys.exit(f"unexpected Korean group: {by_group.get(KOREAN_GROUP)}")
    encs = [{"name": n} for n in MULTI_BYTE_WIRED]
    index = indexes["gb18030"]
    if len(index) != 23940:  # 126 lead bytes (0x81..0xFE) x 190 trail pointers
        sys.exit(f"gb18030 index: expected 23940 entries, got {len(index)}")
    ranges = indexes["gb18030-ranges"]
    if len(ranges) != 207 or any(len(pair) != 2 for pair in ranges):
        sys.exit(f"gb18030 ranges: expected 207 pairs, got {len(ranges)}")
    # The decoder algorithm needs "last pointer <= p"; the encoder needs
    # "last code point <= cp". Both tables are ascending in both columns,
    # which the binary searches in gbk.mbt rely on — assert it here.
    ptrs = [p for p, _ in ranges]
    cps = [c for _, c in ranges]
    if ptrs != sorted(ptrs) or cps != sorted(cps):
        sys.exit("gb18030 ranges are not ascending in both columns")

    parts = [HEADER]
    n_err = sum(1 for cp in index if cp is None)
    print(
        f"gen_chinese: names={[e['name'] for e in encs]} "
        f"index={len(index)} entries ({n_err} null), ranges={len(ranges)} pairs"
    )
    parts.append("// Multi-byte encodings wired in this build (see MULTI_BYTE_WIRED).")
    parts.append("")
    parts.append("///|")
    parts.append("let multi_byte_names : Array[String] = [")
    for enc in encs:
        parts.append(f'  "{enc["name"]}",')
    parts.append("]")
    parts.append("")
    parts.append(
        "// index gb18030: pointer (lead-0x81)*190 + trail -> code point; -1 = error"
    )
    parts.append("")
    parts.append("///|")
    parts.append("let gb18030_index : Array[Int] =")
    parts.append(fmt_array([f"0x{cp:04X}" if cp is not None else "-1" for cp in index], per_line=12))
    parts.append("")
    parts.append(
        "// index gb18030 ranges: (pointer, code point) pairs, both columns ascending."
    )
    parts.append("")
    parts.append("///|")
    parts.append("let gb18030_ranges : Array[Int] =")
    flat = []
    for p, c in ranges:
        flat.append(str(p))
        flat.append(f"0x{c:04X}")
    parts.append(fmt_array(flat, per_line=8))
    parts.append("")
    parts.append(
        "// encoder index: (code point, first pointer) pairs sorted by code point."
    )
    parts.append("// The raw index is not sorted and contains duplicates; the spec's")
    parts.append("// index pointer takes the FIRST occurrence, which this first-wins map encodes.")
    parts.append("")
    parts.append("///|")
    parts.append("let gb18030_encode_index : Array[Int] =")
    first = {}
    for pointer, cp in enumerate(index):  # array position IS the pointer
        if cp is not None and cp not in first:
            first[cp] = pointer
    rev = []
    for cp in sorted(first):
        rev.append(f"0x{cp:04X}")
        rev.append(str(first[cp]))
    print(f"gen_chinese: encode reverse map = {len(first)} unique code points")
    parts.append(fmt_array(rev, per_line=8))
    parts.append("")
    return "\n".join(parts)


def index_key_of(name: str) -> str:
    if name in INDEX_KEY_ALIAS:
        return INDEX_KEY_ALIAS[name]
    key = name.lower().replace("_", "-")
    return key


def mangle(name: str) -> str:
    return name.upper().replace("-", "_").replace(" ", "_").replace(".", "_")


def fmt_array(values, per_line=8):
    chunks = [values[i : i + per_line] for i in range(0, len(values), per_line)]
    body = ",\n".join("  " + ", ".join(chunk) for chunk in chunks)
    return "[\n" + body + ",\n]"


def gen_labels(encodings) -> str:
    lines = [
        HEADER,
        "fn label_lookup(lowercase_label : String) -> Option[String] {",
        "  match lowercase_label {",
    ]
    n = 0
    for heading in encodings:
        for enc in heading["encodings"]:
            for label in enc["labels"]:
                # MoonBit match arms are separated by newlines, not commas.
                lines.append(f'    "{label}" => Some("{enc["name"]}")')
                n += 1
    lines += ["    _ => None", "  }", "}", ""]
    print(f"gen_label: {n} labels -> {sum(len(h['encodings']) for h in encodings)} encodings")
    return "\n".join(lines)


def gen_single_byte(encodings, indexes) -> str:
    encs = single_byte_encodings(encodings)
    parts = [HEADER]
    total_errors = 0
    for enc in encs:
        name = enc["name"]
        key = index_key_of(name)
        if key not in indexes:
            sys.exit(f"{name}: no index table (resolved key {key!r})")
        index = indexes[key]  # 128 entries: bytes 0x80..0xFF -> code point | null
        if len(index) != 128:
            sys.exit(f"{name}: expected 128 index entries, got {len(index)}")
        # The standard's encoder index pointer picks the first occurrence, so
        # duplicate code points would need lowest-byte priority. None of the
        # WHATWG single-byte indexes contain duplicates today — assert rather
        # than silently deduplicate, so an upstream change fails loudly.
        values = [cp for cp in index if cp is not None]
        if len(values) != len(set(values)):
            dup = sorted({cp for cp in values if values.count(cp) > 1})
            sys.exit(f"{name}: duplicate code points in index: {[hex(c) for c in dup]}")
        decode = [f"0x{cp:04X}" if cp is not None else str(ERROR) for cp in index]
        # reverse index for encoding: (code point, byte) pairs sorted by code point
        pairs = sorted((cp, i + 0x80) for i, cp in enumerate(index) if cp is not None)
        reverse = []
        for cp, byte in pairs:
            reverse.append(f"0x{cp:04X}")
            reverse.append(str(byte))
        n_errors = sum(1 for cp in index if cp is None)
        total_errors += n_errors
        var = mangle(name).lower()
        print(
            f"gen_single_byte: {name:16s} index={key:16s} "
            f"decode-error bytes={n_errors:2d} encodable high bytes={len(pairs)}"
        )
        parts.append(f"// {name}: byte 0x80..0xFF -> code point; -1 = decode error -> U+FFFD")
        parts.append("")
        parts.append("///|")
        parts.append(f"let {var}_decode : Array[Int] = {fmt_array(decode)}")
        parts.append("")
        parts.append(f"// {name}: (code point, byte) pairs sorted by code point, for encoding")
        parts.append("")
        parts.append("///|")
        parts.append(f"let {var}_encode : Array[Int] = {fmt_array(reverse)}")
        parts.append("")

    # Dispatch: codec.mbt resolves an encoding name to its generated tables
    # here, keeping the wired set in lockstep with the generated data.
    parts.append("// Encoding names wired by this build (same source as the dispatch below).")
    parts.append("")
    parts.append("///|")
    parts.append("let single_byte_names : Array[String] = [")
    for enc in encs:
        parts.append(f'  "{enc["name"]}",')
    parts.append("]")
    parts.append("")
    parts.append("// Dispatch from WHATWG encoding name to generated tables (codec.mbt).")
    parts.append("")
    parts.append("///|")
    parts.append(
        "fn single_byte_tables(encoding : String) -> Option[(Array[Int], Array[Int])] {"
    )
    parts.append("  match encoding {")
    for enc in encs:
        var = mangle(enc["name"]).lower()
        parts.append(
            f'    "{enc["name"]}" => Some(({var}_decode, {var}_encode))'
        )
    parts.append("    _ => None")
    parts.append("  }")
    parts.append("}")
    parts.append("")
    print(
        f"gen_single_byte: {len(encs)} encodings, "
        f"{total_errors} decode-error bytes total, dispatch emitted"
    )
    return "\n".join(parts)


def flatten_pairs(mapping) -> list:
    out = []
    for cp in sorted(mapping):
        out.append("0x%04X" % cp)
        out.append(str(mapping[cp]))
    return out


def gen_big5_sjis(indexes) -> str:
    """Tables for Big5 and Shift_JIS (encoding.bs §big5 / §shift_jis).

    Big5 decode: positional index Big5 (19782 = 126 leads x 157 trails).
    Big5 encode: index Big5 pointer over the filtered index (pointer >=
    (0xA1-0x81)*157, dropping the low/HKSCS rows the spec tells encoders to
    avoid), first occurrence — EXCEPT the six code points where the spec
    wants the LAST pointer.

    Shift_JIS decode: index jis0208 read at the Shift_JIS pointer; the spec
    notes this index has an alternative Shift_JIS visualization, i.e. one
    shared pointer space (188 slots per lead = two 94-column rows).
    Shift_JIS encode: same index excluding pointers 8272..8835 (NEC
    duplicate rows), first occurrence.
    """
    big5 = indexes["big5"]
    jis = indexes["jis0208"]
    if len(big5) != 19782:
        sys.exit(f"big5 index: expected 19782 entries, got {len(big5)}")
    if len(jis) != 11280:
        sys.exit(f"jis0208 index: expected 11280 entries, got {len(jis)}")

    # Encode-map rules live in multibyte_ref (shared with the differential
    # reference); assert the spec's six last-pointer code points survived.
    big5_enc = multibyte_ref.big5_encode_map(big5)
    missing = set(multibyte_ref.BIG5_SIX) - set(big5_enc)
    if missing:
        sys.exit(f"Big5 six-cps absent from filtered index: {sorted(map(hex, missing))}")
    sjis_enc = multibyte_ref.sjis_encode_map(jis)

    parts = [HEADER]
    n_big5_null = sum(1 for cp in big5 if cp is None)
    n_jis_null = sum(1 for cp in jis if cp is None)
    print(
        f"gen_big5_sjis: big5 index={len(big5)} ({n_big5_null} null), encode={len(big5_enc)} cps; "
        f"jis0208={len(jis)} ({n_jis_null} null), sjis encode={len(sjis_enc)} cps"
    )

    def emit(name, var, values, per_line=12):
        parts.append(f"// {name}")
        parts.append("")
        parts.append("///|")
        parts.append(f"let {var} : Array[Int] =")
        parts.append(fmt_array(values, per_line=per_line))
        parts.append("")

    emit(
        "index Big5: pointer (lead-0x81)*157 + trail -> code point; -1 = error",
        "big5_index",
        ["0x%04X" % cp if cp is not None else "-1" for cp in big5],
    )
    emit(
        "index Big5 encoder reverse: (code point, pointer); pointer >= 5024, "
        "the six spec code points use their LAST pointer",
        "big5_encode_index",
        flatten_pairs(big5_enc),
        per_line=8,
    )
    emit(
        "index jis0208 (shared EUC-JP / Shift_JIS pointer space): "
        "Shift_JIS pointer -> code point; -1 = error",
        "jis0208_index",
        ["0x%04X" % cp if cp is not None else "-1" for cp in jis],
    )
    emit(
        "index Shift_JIS encoder reverse: (code point, pointer); pointers "
        "8272..8835 (NEC duplicate rows) excluded, first occurrence wins",
        "shift_jis_encode_index",
        flatten_pairs(sjis_enc),
        per_line=8,
    )
    return "\n".join(parts)


def gen_euc(indexes) -> str:
    """Tables for EUC-JP and EUC-KR (encoding.bs §euc-jp / §euc-kr).

    EUC-JP decode reads the SHARED jis0208 table (already emitted in
    gen_big5_sjis.mbt — one pointer space,188 slots/lead for Shift_JIS vs
    94 columns here) plus jis0212 for SS3 sequences; its encoder reverse
    is a plain first-wins map whose maximum pointer is asserted < 8836
    per the spec's own note. EUC-KR uses its 23940-entry index with no
    duplicate code points, so its encoder map is the identity.
    """
    jis212 = indexes["jis0212"]
    euc_kr = indexes["euc-kr"]
    if len(jis212) != 8836:
        sys.exit(f"jis0212 index: expected 8836 entries, got {len(jis212)}")
    if len(euc_kr) != 23940:
        sys.exit(f"euc-kr index: expected 23940 entries, got {len(euc_kr)}")

    euc_jp_enc = multibyte_ref.euc_jp_encode_map(indexes["jis0208"])  # asserts < 8836
    euc_kr_enc = multibyte_ref.euc_kr_encode_map(euc_kr)

    parts = [HEADER]
    print(
        f"gen_euc: jis0212={len(jis212)} ({sum(1 for x in jis212 if x is None)} null), "
        f"euc_jp encode={len(euc_jp_enc)} cps (max ptr {max(euc_jp_enc.values())}), "
        f"euc_kr={len(euc_kr)} ({sum(1 for x in euc_kr if x is None)} null), "
        f"euc_kr encode={len(euc_kr_enc)} cps"
    )

    def emit(name, var, values, per_line=12):
        parts.append(f"// {name}")
        parts.append("")
        parts.append("///|")
        parts.append(f"let {var} : Array[Int] =")
        parts.append(fmt_array(values, per_line=per_line))
        parts.append("")

    emit(
        "index jis0212 (EUC-JP SS3 / 0x8F sequences): (lead-0xA1)*94 + trail-0xA1 "
        "-> code point; -1 = error",
        "jis0212_index",
        ["0x%04X" % cp if cp is not None else "-1" for cp in jis212],
    )
    emit(
        "index EUC-KR: pointer (lead-0x81)*190 + trail-0x41 -> code point; -1 = error",
        "euc_kr_index",
        ["0x%04X" % cp if cp is not None else "-1" for cp in euc_kr],
    )
    emit(
        "index EUC-KR encoder reverse: (code point, pointer); no duplicate code "
        "points in the index",
        "euc_kr_encode_index",
        flatten_pairs(euc_kr_enc),
        per_line=8,
    )
    emit(
        "index jis0208 encoder reverse for EUC-JP: (code point, pointer), first "
        "occurrence; all pointers < 8836 per the spec's note (asserted at "
        "generation time). Differs from the Shift_JIS map, which excludes "
        "pointers 8272..8835",
        "euc_jp_encode_index",
        flatten_pairs(euc_jp_enc),
        per_line=8,
    )
    return "\n".join(parts)


def main():
    encodings, indexes = load_sources()
    (ROOT / "gen_label.mbt").write_text(gen_labels(encodings), encoding="utf-8", newline="\n")
    (ROOT / "gen_single_byte.mbt").write_text(
        gen_single_byte(encodings, indexes), encoding="utf-8", newline="\n"
    )
    (ROOT / "gen_chinese.mbt").write_text(
        gen_chinese(encodings, indexes), encoding="utf-8", newline="\n"
    )
    (ROOT / "gen_big5_sjis.mbt").write_text(
        gen_big5_sjis(indexes), encoding="utf-8", newline="\n"
    )
    (ROOT / "gen_euc.mbt").write_text(
        gen_euc(indexes), encoding="utf-8", newline="\n"
    )
    print(
        "wrote gen_label.mbt, gen_single_byte.mbt, gen_chinese.mbt, "
        "gen_big5_sjis.mbt, gen_euc.mbt"
    )


if __name__ == "__main__":
    main()
