#!/usr/bin/env python3
"""Generate MoonBit table sources from the vendored WHATWG encoding data.

Usage:
    python tools/generate_tables.py

Reads tools/data/encodings.json and tools/data/indexes.json (vendored from
whatwg/encoding @ 2c3853e — the same revision encoding_rs pins for its own
table generation) and writes gen_label.mbt / gen_single_byte.mbt to the
repository root.

gen_single_byte.mbt contains, for every encoding in the WHATWG
"Legacy single-byte encodings" group:
- a decode table (byte 0x80..0xFF -> code point, -1 = index null = decode
  error -> U+FFFD under the standard's replacement semantics),
- an encode table (code point, byte pairs sorted by code point),
plus the `single_byte_tables` dispatch that codec.mbt uses, so the set of
wired encodings can never drift from the generated tables.

Emission is in moon fmt's fixpoint shape (comment block, blank line, `///|`
doc marker, declaration): moon 0.1.20260915's comment promotion needs two
fmt passes otherwise, and the CI freshness check only formats once.

DO NOT edit the generated files by hand; re-run this script instead.
CI regenerates, runs `moon fmt`, and fails if the result differs from what
is committed.
"""

import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
DATA = HERE / "data"

REV = "2c3853e461afd718be198772170d024e427aee21"
SOURCE_URL = "https://github.com/whatwg/encoding"

HEADER = f"""// Generated by tools/generate_tables.py — DO NOT EDIT.
//
// Source: {SOURCE_URL} @ {REV}
// Data © WHATWG (Apple, Google, Mozilla, Microsoft); BSD 3-Clause License
// (see LICENSE-WHATWG in this repository).
"""

SINGLE_BYTE_GROUP = "Legacy single-byte encodings"

# Encoding name -> indexes.json key, where they differ. ISO-8859-8-I shares
# the ISO-8859-8 index (it is the logical-order label variant; the standard
# defines both against the same table).
INDEX_KEY_ALIAS = {"ISO-8859-8-I": "iso-8859-8"}

# Sentinel in decode tables: WHATWG index entry "null" -> decode error -> U+FFFD.
ERROR = -1


def load_sources():
    encodings = json.loads((DATA / "encodings.json").read_text(encoding="utf-8"))
    indexes = json.loads((DATA / "indexes.json").read_text(encoding="utf-8"))
    return encodings, indexes


def single_byte_encodings(encodings) -> list:
    for heading in encodings:
        if heading["heading"] == SINGLE_BYTE_GROUP:
            return list(heading["encodings"])
    sys.exit(f"encodings.json has no {SINGLE_BYTE_GROUP!r} group")


def index_key_of(name: str) -> str:
    if name in INDEX_KEY_ALIAS:
        return INDEX_KEY_ALIAS[name]
    key = name.lower().replace("_", "-")
    return key


def mangle(name: str) -> str:
    return name.upper().replace("-", "_").replace(" ", "_").replace(".", "_")


def fmt_array(values, per_line=8):
    chunks = [values[i : i + per_line] for i in range(0, len(values), per_line)]
    body = ",\n".join("  " + ", ".join(chunk) for chunk in chunks)
    return "[\n" + body + ",\n]"


def gen_labels(encodings) -> str:
    lines = [
        HEADER,
        "fn label_lookup(lowercase_label : String) -> Option[String] {",
        "  match lowercase_label {",
    ]
    n = 0
    for heading in encodings:
        for enc in heading["encodings"]:
            for label in enc["labels"]:
                # MoonBit match arms are separated by newlines, not commas.
                lines.append(f'    "{label}" => Some("{enc["name"]}")')
                n += 1
    lines += ["    _ => None", "  }", "}", ""]
    print(f"gen_label: {n} labels -> {sum(len(h['encodings']) for h in encodings)} encodings")
    return "\n".join(lines)


def gen_single_byte(encodings, indexes) -> str:
    encs = single_byte_encodings(encodings)
    parts = [HEADER]
    total_errors = 0
    for enc in encs:
        name = enc["name"]
        key = index_key_of(name)
        if key not in indexes:
            sys.exit(f"{name}: no index table (resolved key {key!r})")
        index = indexes[key]  # 128 entries: bytes 0x80..0xFF -> code point | null
        if len(index) != 128:
            sys.exit(f"{name}: expected 128 index entries, got {len(index)}")
        # The standard's encoder index pointer picks the first occurrence, so
        # duplicate code points would need lowest-byte priority. None of the
        # WHATWG single-byte indexes contain duplicates today — assert rather
        # than silently deduplicate, so an upstream change fails loudly.
        values = [cp for cp in index if cp is not None]
        if len(values) != len(set(values)):
            dup = sorted({cp for cp in values if values.count(cp) > 1})
            sys.exit(f"{name}: duplicate code points in index: {[hex(c) for c in dup]}")
        decode = [f"0x{cp:04X}" if cp is not None else str(ERROR) for cp in index]
        # reverse index for encoding: (code point, byte) pairs sorted by code point
        pairs = sorted((cp, i + 0x80) for i, cp in enumerate(index) if cp is not None)
        reverse = []
        for cp, byte in pairs:
            reverse.append(f"0x{cp:04X}")
            reverse.append(str(byte))
        n_errors = sum(1 for cp in index if cp is None)
        total_errors += n_errors
        var = mangle(name).lower()
        print(
            f"gen_single_byte: {name:16s} index={key:16s} "
            f"decode-error bytes={n_errors:2d} encodable high bytes={len(pairs)}"
        )
        parts.append(f"// {name}: byte 0x80..0xFF -> code point; -1 = decode error -> U+FFFD")
        parts.append("")
        parts.append("///|")
        parts.append(f"let {var}_decode : Array[Int] = {fmt_array(decode)}")
        parts.append("")
        parts.append(f"// {name}: (code point, byte) pairs sorted by code point, for encoding")
        parts.append("")
        parts.append("///|")
        parts.append(f"let {var}_encode : Array[Int] = {fmt_array(reverse)}")
        parts.append("")

    # Dispatch: codec.mbt resolves an encoding name to its generated tables
    # here, keeping the wired set in lockstep with the generated data.
    parts.append("// Encoding names wired by this build (same source as the dispatch below).")
    parts.append("")
    parts.append("///|")
    parts.append("let single_byte_names : Array[String] = [")
    for enc in encs:
        parts.append(f'  "{enc["name"]}",')
    parts.append("]")
    parts.append("")
    parts.append("// Dispatch from WHATWG encoding name to generated tables (codec.mbt).")
    parts.append("")
    parts.append("///|")
    parts.append(
        "fn single_byte_tables(encoding : String) -> Option[(Array[Int], Array[Int])] {"
    )
    parts.append("  match encoding {")
    for enc in encs:
        var = mangle(enc["name"]).lower()
        parts.append(
            f'    "{enc["name"]}" => Some(({var}_decode, {var}_encode))'
        )
    parts.append("    _ => None")
    parts.append("  }")
    parts.append("}")
    parts.append("")
    print(
        f"gen_single_byte: {len(encs)} encodings, "
        f"{total_errors} decode-error bytes total, dispatch emitted"
    )
    return "\n".join(parts)


def main():
    encodings, indexes = load_sources()
    (ROOT / "gen_label.mbt").write_text(gen_labels(encodings), encoding="utf-8", newline="\n")
    (ROOT / "gen_single_byte.mbt").write_text(
        gen_single_byte(encodings, indexes), encoding="utf-8", newline="\n"
    )
    print("wrote gen_label.mbt, gen_single_byte.mbt")


if __name__ == "__main__":
    main()
